services:
  rabbitmq:
    image: rabbitmq:latest
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - app-network

  php:
    build:
      context: .
      dockerfile: php/Dockerfile
    volumes:
      - ./src:/var/www/html/src
    ports:
      - "8000:80"
    depends_on:
      - rabbitmq
    networks:
      - app-network

networks:
  app-network:
    driver: bridge